version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_docker_spring_lab
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_docker_spring_lab_docker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_docker_spring_lab
    restart: always
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data:
